import 'dart:io';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class HistoryScreen extends StatefulWidget {
  const HistoryScreen({super.key});

  @override
  State<HistoryScreen> createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> {
  List<Map<String, dynamic>> _scanHistory = [];

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  Future<void> _loadHistory() async {
    final prefs = await SharedPreferences.getInstance();
    List<String> rawHistory = prefs.getStringList('scan_history') ?? [];

    setState(() {
      _scanHistory = rawHistory
          .map((item) => jsonDecode(item) as Map<String, dynamic>)
          .toList();
    });
  }

  Future<void> _exportCSV() async {
    if (_scanHistory.isEmpty) return;

    // 1. Fetch user data for the CSV header
    final prefs = await SharedPreferences.getInstance();
    String userName = prefs.getString('userName') ?? 'Unknown User';
    String userOrg = prefs.getString('userOrg') ?? 'Unknown Org';

    // 2. Build the CSV Rows
    List<List<dynamic>> rows = [];
    rows.add(["Report Generated By:", userName, "Organization:", userOrg]);
    rows.add([]); // Empty row
    rows.add([
      "Date/Time",
      "Grade",
      "Broken %",
      "Shape",
      "Total Grains",
      "Avg Length (mm)"
    ]);

    for (var scan in _scanHistory) {
      rows.add([
        scan['date'],
        scan['grade'],
        scan['brokenPercent'],
        scan['shape'],
        scan['totalGrains'],
        scan['length'],
      ]);
    }

    // 3. Convert to CSV string
    String csvData = const ListToCsvConverter().convert(rows);

    // 4. Save to a temporary file
    final directory = await getTemporaryDirectory();
    final path = "${directory.path}/rice_quality_report.csv";
    final file = File(path);
    await file.writeAsString(csvData);

    // 5. Trigger the phone's native Share/Export menu
    await Share.shareXFiles([XFile(path)],
        text: 'Attached is the latest Rice Quality Scan Report.');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan History',
            style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.green,
        foregroundColor: Colors.white,
      ),
      body: _scanHistory.isEmpty
          ? const Center(child: Text('No scans yet. Run your first analysis!'))
          : ListView.builder(
              padding: const EdgeInsets.all(12),
              itemCount: _scanHistory.length,
              itemBuilder: (context, index) {
                var scan = _scanHistory[index];
                return Card(
                  elevation: 2,
                  margin: const EdgeInsets.only(bottom: 12),
                  child: ListTile(
                    leading: const Icon(Icons.history,
                        color: Colors.green, size: 30),
                    title: Text(
                        '${scan['grade']} - ${scan['brokenPercent']}% Broken',
                        style: const TextStyle(fontWeight: FontWeight.bold)),
                    subtitle:
                        Text('Date: ${scan['date']} | Shape: ${scan['shape']}'),
                    trailing: Text('${scan['totalGrains']}\ngrains',
                        textAlign: TextAlign.center),
                  ),
                );
              },
            ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _exportCSV,
        backgroundColor: Colors.green,
        foregroundColor: Colors.white,
        icon: const Icon(Icons.download),
        label: const Text('Export CSV'),
      ),
    );
  }
}
